export const distribuidores: Array<DistribuidorType> = [
  {
    idDistribuidor: 'Cambalache',
    nombre: 'Asociación Cambalache',
    entregados: 20,
    existencias: 20,
    localidad: 'Oviedo',
    contacto: 'Germán',
    telefono: '985 20 22 92',
    email: 'cambalache@localcambalache.org',
    direccion: 'c/Martínez Vigil 30, bajo\n33010 Oviedo - Asturias',
  },
  {
    idDistribuidor: 'Swinton',
    nombre: 'Swinton & Grant',
    entregados: 3,
    existencias: 3,
    localidad: 'Madrid',
    contacto: 'Goyo  ',
    telefono: '659 479 421',
    email: 'aloha@swintonandgrant.com',
    direccion:
      'Factura: Bit Flow Studio S. L. \nc/ Miguel Servet 21 - B 85849065',
  },
  {
    idDistribuidor: 'Lluvia',
    nombre: 'El Olor de la Lluvia',
    entregados: 10,
    vendidos: 4,
    existencias: 6,
    localidad: 'Madrid',
    contacto: 'Raquel y Alfonso ',
    telefono: '91 138 9054',
    email: 'libreria@elolordelalluvia',
    direccion: 'c/ de las Maldonadas 6  - E 87413407',
  },
  {
    idDistribuidor: 'Olivia',
    nombre: 'Ed Olivia ',
    entregados: 55,
    vendidos: 14,
    existencias: 41,
    localidad: 'Buenos Aires',
    contacto: 'Adrián Scotto',
    telefono: '0054 9 11 3202 6709',
    email: 'info@editorialolivia.com',
    direccion: 'Esmeralda 980 1º B \nC.A.B.A. (C1007ABJ) Argentina',
  },
  {
    idDistribuidor: 'Alibri',
    nombre: 'Alibri',
    entregados: 16,
    vendidos: 7,
    existencias: 9,
    localidad: 'Barcelona',
    contacto: 'Andrés ',
    telefono: '93 317 0578',
    direccion: 'Carrer de Balmes, 26  - Barcelona',
  },
  {
    idDistribuidor: 'TeQuiero',
    nombre: 'Té Quiero',
    entregados: 20,
    vendidos: 12,
    existencias: 8,
    localidad: 'Barcelona',
    contacto: 'Iris / Chelo  ',
    telefono: '93 284 6000',
    email: 'libreríatequiero@yahoo.es',
    direccion: 'Carrer de Torrijos, 9 - Barcelona\nNIF 38062310R',
  },
  {
    idDistribuidor: 'LosAngeles',
    nombre: 'Librería Los Ángeles',
    entregados: 8,
    vendidos: 4,
    existencias: 4,
    localidad: 'Barcelona',
    contacto: 'María del Pilar',
    telefono: '932 18 89 86',
    email: 'Travessera de Gràcia, 157  ',
  },
  {
    idDistribuidor: 'Dharani',
    nombre: 'Dharani',
    entregados: 4,
    existencias: 4,
    localidad: 'Sitges',
    contacto: ' ',
  },
  {
    idDistribuidor: 'BioSitges',
    nombre: 'BioSitges',
    entregados: 4,
    vendidos: 1,
    existencias: 3,
    localidad: 'Sitges',
  },
  {
    idDistribuidor: 'Alfamar',
    nombre: 'Alfamar 4 libros',
    entregados: 7,
    vendidos: 4,
    existencias: 3,
    localidad: 'Barcelona',
    contacto: 'Emilio  ',
    telefono: '93 318 8453',
    direccion: 'Carrer de Roger de Llúria, 46',
  },
  {
    idDistribuidor: 'SimpleCat',
    nombre: 'Simple.cat',
    vendidos: 30,
    existencias: -30,
    localidad: 'Barcelona',
    telefono: '656 966 373',
    email: 'enric@simple.cat',
    direccion:
      ' C/Joan Ramon Benaprès, 15, 1-1 - 08870 SITGES\nNIF: 35.111.953S ',
  },
  {
    idDistribuidor: 'Gabalda',
    nombre: 'Gabaldà',
    entregados: 8,
    vendidos: 3,
    existencias: 5,
    localidad: 'Sant Pere',
    telefono: '93 896 02 51',
    email: 'llibreria.gabalda@gmail.com',
    direccion: 'Plaça de la Vila 8, Sant Pere de Ribes\nCIF/NIF 77081261G',
  },
  {
    idDistribuidor: 'Mulassa',
    nombre: 'La Mulassa',
    entregados: 6,
    existencias: 6,
    localidad: 'Vilanova i la Geltrú',
    contacto: 'Berta Chivite',
    telefono: '93 814 48 46',
    email:
      'info@llibrerialamulassa.cat\npresentación: anna@llibrerialamulassa.cat',
    direccion: 'Rambla Principal 2, Vilanova i la Geltrú\nB62197165',
  },
  {
    idDistribuidor: 'Tatiana',
    nombre: 'Tatiana Sibilia',
    entregados: 20,
    vendidos: 5,
    existencias: 15,
    localidad: 'Barcelona',
    telefono: '671 843 924',
  },
  {
    idDistribuidor: 'Encarna',
    nombre: 'Encarna Martínez',
    entregados: 10,
    existencias: 10,
    localidad: 'Barcelona',
    contacto: 'Encarna Martínez',
    telefono: '607 112 743',
  },
  {
    idDistribuidor: 'Clara',
    nombre: 'Clara Rodriguez',
    entregados: 10,
    vendidos: 10,
    localidad: 'Madrid',
    contacto: 'Clara Rodriguez',
    telefono: '636 613 886',
    direccion: 'Calle Francisco Rabal 2, 2-C\n28901 Getafe Madrid',
  },
  {
    idDistribuidor: 'Ansara',
    nombre: 'Ansara',
    entregados: 1,
    existencias: 1,
  },
  {
    idDistribuidor: 'Maya',
    nombre: 'La Mano de Maya',
    entregados: 5,
    existencias: 5,
    localidad: 'Sitges',
    contacto: 'Laia',
    telefono: '93 510 48 89',
    email: 'info@lamanodemaya.com',
    direccion: 'Carrer de Sant Josep, 36-38 MEXCALI, S.L. B66529702',
  },
  {
    idDistribuidor: 'Beatriz',
    nombre: 'Beatriz Oliva',
    entregados: 10,
    existencias: 10,
    localidad: 'Asturias',
    contacto: 'Beatriz',
    telefono: '696 512 564',
    email: 'bogrupos@gmail.com',
    direccion: 'Avenida María Faes 15 Siero 33519  Asturias',
  },
  {
    idDistribuidor: 'Olympia',
    nombre: 'Olympia',
    entregados: 4,
    existencias: 4,
    telefono: '616 335 060',
  },
];
